export enum Pais {

    AFEGANISTAO = "AFEGANISTAO",
    AFRICA_DO_SUL = "AFRICA_DO_SUL do Sul",
    ALBANIA = "ALBANIA",
    ALEMANHA = "ALEMANHA",
    ANDORRA = "ANDORRA",
    ANGOLA = "ANGOLA",
    ANGUILLA = "ANGUILLA",
    ANTARTIDA = "ANTARTIDA",
    ANTIGUA_E_BARBUDA = "ANTIGUA_E_BARBUDA",
    ARABIA_SAUDITA = "ARABIA_SAUDITA",
    ARGELIA = "ARGELIA",
    ARGENTINA = "ARGENTINA",
    ARMENIA = "ARMENIA",
    ARUBA = "ARUBA",
    AUSTRALIA = "AUSTRALIA",
    AUSTRIA = "AUSTRIA",
    AZERBAIJAO = "AZERBAIJAO",
    BAHAMAS = "BAHAMAS",
    BAHREIN = "BAHREIN",
    BANGLADESH = "BANGLADESH",
    BARBADOS = "BARBADOS",
    BELARUS = "BELARUS",
    BELGICA = "BELGICA",
    BELIZE = "BELIZE",
    BENIN = "BENIN",
    BERMUDA = "BERMUDA",
    BOLIVIA = "BOLIVIA",
    BOSNIA_E_HERZEGOVINA = "BOSNIA_E_HERZEGOVINA",
    BOTSWANA = "BOTSWANA",
    BRASIL = "BRASIL",
    BRUNEI = "BRUNEI",
    BULGARIA = "BULGARIA",
    BURKINA_FASO = "BURKINA_FASO",
    BURUNDI = "BURUNDI",
    BUTAO = "BUTAO",
    CABO_VERDE = "CABO_VERDE",
    CAMAROES = "CAMAROES",
    CAMBOJA = "CAMBOJA",
    CANADA = "CANADA",
    CATAR = "CATAR",
    CAZAQUISTAO = "CAZAQUISTAO",
    CHADE = "CHADE",
    CHILE = "CHILE",
    CHINA = "CHINA",
    CHIPRE = "CHIPRE",
    COLOMBIA = "COLOMBIA",
    COMORES = "COMORES",
    CONGO = "CONGO",
    COREIA_DO_NORTE = "COREIA_DO_NORTE",
    COREIA_DO_SUL = "COREIA_DO_SUL",
    COSTA_DO_MARFIM = "COSTA_DO_MARFIM",
    COSTA_RICA = "COSTA_RICA",
    CROACIA = "CROACIA",
    CUBA = "CUBA",
    CURACAO = "CURACAO",
    DINAMARCA = "DINAMARCA",
    DJIBOUTI = "DJIBOUTI",
    DOMINICA = "DOMINICA",
    EGITO = "EGITO",
    EL_SALVADOR = "EL_SALVADOR",
    EMIRADOS_ARABES_UNIDOS = "EMIRADOS_ARABES_UNIDOS",
    EQUADOR = "EQUADOR",
    ERITREIA = "ERITREIA",
    ESLOVAQUIA = "ESLOVAQUIA",
    ESLOVENIA = "ESLOVENIA",
    ESPANHA = "ESPANHA",
    ESTADOS_UNIDOS = "ESTADOS_UNIDOS",
    ESTONIA = "ESTONIA",
    ETIOPIA = "ETIOPIA",
    FIJI = "FIJI",
    FILIPINAS = "FILIPINAS",
    FINLANDIA = "FINLANDIA",
    FRANCA = "FRANCA",
    GABAO = "GABAO",
    GAMBIA = "GAMBIA",
    GANA = "GANA",
    GEORGIA = "GEORGIA",
    GIBRALTAR = "GIBRALTAR",
    GRANADA = "GRANADA",
    GRECIA = "GRECIA",
    GROENLANDIA = "GROENLANDIA",
    GUADALUPE = "GUADALUPE",
    GUAM = "GUAM",
    GUATEMALA = "GUATEMALA",
    GUERNSEY = "GUERNSEY",
    GUINE = "GUINE",
    GUINE_BISSAU = "GUINE_BISSAU",
    GUINE_EQUATORIAL = "GUINE_EQUATORIAL",
    GUIANA = "GUIANA",
    GUIANA_FRANCESA = "GUIANA_FRANCESA",
    HAITI = "HAITI",
    HONDURAS = "HONDURAS",
    HONG_KONG = "HONG_KONG",
    HUNGRIA = "HUNGRIA",
    IEMEN = "IEMEN",
    ILHAS_CAYMAN = "ILHAS_CAYMAN",
    ILHAS_COOK = "ILHAS_COOK",
    ILHAS_FALKLAND = "ILHAS_FALKLAND",
    ILHAS_MARSHALL = "ILHAS_MARSHALL",
    ILHAS_SALOMAO = "ILHAS_SALOMAO",
    ILHAS_TURCAS_E_CAICOS = "ILHAS_TURCAS_E_CAICOS",
    ILHAS_VIRGENS_AMERICANAS = "ILHAS_VIRGENS_AMERICANAS",
    ILHAS_VIRGENS_BRITANICAS = "ILHAS_VIRGENS_BRITANICAS",
    INDIA = "INDIA",
    INDONESIA = "INDONESIA",
    IRA = "IRA",
    IRAQUE = "IRAQUE",
    IRLANDA = "IRLANDA",
    ISLANDIA = "ISLANDIA",
    ISRAEL = "ISRAEL",
    ITALIA = "ITALIA",
    JAMAICA = "JAMAICA",
    JAPAO = "JAPAO",
    JERSEY = "JERSEY",
    JORDANIA = "JORDANIA",
    KAZAQUISTAO = "KAZAQUISTAO",
    KIRIBATI = "KIRIBATI",
    KUWAIT = "KUWAIT",
    LAOS = "LAOS",
    LESOTO = "LESOTO",
    LETONIA = "LETONIA",
    LIBANO = "LIBANO",
    LIBERIA = "LIBERIA",
    LIBIA = "LIBIA",
    LIECHTENSTEIN = "LIECHTENSTEIN",
    LITUANIA = "LITUANIA",
    LUXEMBURGO = "LUXEMBURGO",
    MACAU = "MACAU",
    MADAGASCAR = "MADAGASCAR",
    MALASIA = "MALASIA",
    MALAUI = "MALAUI",
    MALDIVAS = "MALDIVAS",
    MALI = "MALI",
    MALTA = "MALTA",
    MARROCOS = "MARROCOS",
    MARTINICA = "MARTINICA",
    MAURICIO = "MAURICIO",
    MAURITANIA = "MAURITANIA",
    MEXICO = "MEXICO",
    MICRONESIA = "MICRONESIA",
    MOCAMBIQUE = "MOCAMBIQUE",
    MOLDOVA = "MOLDOVA",
    MONACO = "MONACO",
    MONGOLIA = "MONGOLIA",
    MONTENEGRO = "MONTENEGRO",
    MONTSERRAT = "MONTSERRAT",
    NAMIBIA = "NAMIBIA",
    NAURU = "NAURU",
    NEPAL = "NEPAL",
    NICARAGUA = "NICARAGUA",
    NIGER = "NIGER",
    NIGERIA = "NIGERIA",
    NIUE = "NIUE",
    NORUEGA = "NORUEGA",
    NOVA_CALEDONIA = "NOVA_CALEDONIA",
    NOVA_ZELANDIA = "NOVA_ZELANDIA",
    OMA = "OMA",
    PAISES_BAIXOS = "PAISES_BAIXOS",
    PALAU = "PALAU",
    PALESTINA = "PALESTINA",
    PANAMA = "PANAMA",
    PAPUA_NOVA_GUINE = "PAPUA_NOVA_GUINE",
    PAQUISTAO = "PAQUISTAO",
    PARAGUAI = "PARAGUAI",
    PERU = "PERU",
    POLINESIA_FRANCESA = "POLINESIA_FRANCESA",
    POLONIA = "POLONIA",
    PORTUGAL = "PORTUGAL",
    PORTO_RICO = "PORTO_RICO",
    QATAR = "QATAR",
    QUENIA = "QUENIA",
    QUIRGUISTAO = "QUIRGUISTAO",
    REUNIAO = "REUNIAO",
    ROMENIA = "ROMENIA",
    RUANDA = "RUANDA",
    RUSSIA = "RUSSIA",
    SALVADOR = "SALVADOR",
    SAMOA = "SAMOA",
    SAN_MARINO = "SAN_MARINO",
    SANTA_HELENA = "SANTA_HELENA",
    SANTA_LUCIA = "SANTA_LUCIA",
    SAO_BARTOLOMEU = "SAO_BARTOLOMEU",
    SAO_CRISTOVAO_E_NEVIS = "SAO_CRISTOVAO_E_NEVIS",
    SAO_TOME_E_PRINCIPE = "SAO_TOME_E_PRINCIPE",
    SAO_VICENTE_E_GRANADINAS = "SAO_VICENTE_E_GRANADINAS",
    SENEGAL = "SENEGAL",
    SERVIA = "SERVIA",
    SEYCHELLES = "SEYCHELLES",
    SERRA_LEOA = "SERRA_LEOA",
    SINGAPURA = "SINGAPURA",
    SIRIA = "SIRIA",
    SOMALIA = "SOMALIA",
    SRI_LANKA = "SRI_LANKA",
    SUAZILANDIA = "SUAZILANDIA",
    SUDAO = "SUDAO",
    SUDAO_DO_SUL = "SUDAO_DO_SUL",
    SUECIA = "SUECIA",
    SUICA = "SUICA",
    SURINAME = "SURINAME",
    TAILANDIA = "TAILANDIA",
    TAIWAN = "TAIWAN",
    TADJIQUISTAO = "TADJIQUISTAO",
    TANZANIA = "TANZANIA",
    TIMOR_LESTE = "TIMOR_LESTE",
    TOGO = "TOGO",
    TONGA = "TONGA",
    TRINIDAD_E_TOBAGO = "TRINIDAD_E_TOBAGO",
    TUNISIA = "TUNISIA",
    TURCOMENISTAO = "TURCOMENISTAO",
    TURQUIA = "TURQUIA",
    TUVALU = "TUVALU",
    UCRANIA = "UCRANIA",
    UGANDA = "UGANDA",
    URUGUAI = "URUGUAI",
    UZBEQUISTAO = "UZBEQUISTAO",
    VANUATU = "VANUATU",
    VATICANO = "VATICANO",
    VENEZUELA = "VENEZUELA",
    VIETNA = "VIETNA",
    ZAMBIA = "ZAMBIA",
    ZIMBABUE = "ZIMBABUE",
}

export const PaisDescricao: Record<Pais, string> = {
    [Pais.AFEGANISTAO]: "Afeganistão",
    [Pais.AFRICA_DO_SUL]: "África do Sul",
    [Pais.ALBANIA]: "Albânia",
    [Pais.ALEMANHA]: "Alemanha",
    [Pais.ANDORRA]: "Andorra",
    [Pais.ANGOLA]: "Angola",
    [Pais.ANGUILLA]: "Anguilla",
    [Pais.ANTARTIDA]: "Antártida",
    [Pais.ANTIGUA_E_BARBUDA]: "Antígua e Barbuda",
    [Pais.ARABIA_SAUDITA]: "Arábia Saudita",
    [Pais.ARGELIA]: "Argélia",
    [Pais.ARGENTINA]: "Argentina",
    [Pais.ARMENIA]: "Armênia",
    [Pais.ARUBA]: "Ar  uba",
    [Pais.AUSTRALIA]: "Austrália",
    [Pais.AUSTRIA]: "Áustria",
    [Pais.AZERBAIJAO]: "Azerbaijão",
    [Pais.BAHAMAS]: "Bahamas",
    [Pais.BAHREIN]: "Bahrein",
    [Pais.BANGLADESH]: "Bangladesh",
    [Pais.BARBADOS]: "Barbados",
    [Pais.BELARUS]: "Belarus",
    [Pais.BELGICA]: "Bélgica",
    [Pais.BELIZE]: "Belize",
    [Pais.BENIN]: "Benin",
    [Pais.BERMUDA]: "Bermuda",
    [Pais.BOLIVIA]: "Bolívia",
    [Pais.BOSNIA_E_HERZEGOVINA]: "Bósnia e Herzegovina",
    [Pais.BOTSWANA]: "Botswana",
    [Pais.BRASIL]: "Brasil",
    [Pais.BRUNEI]: "Brunei",
    [Pais.BULGARIA]: "Bulgária",
    [Pais.BURKINA_FASO]: "Burkina Faso",
    [Pais.BURUNDI]: "Burundi",
    [Pais.BUTAO]: "Butão",
    [Pais.CABO_VERDE]: "Cabo Verde",
    [Pais.CAMAROES]: "Camarões",
    [Pais.CAMBOJA]: "Camboja",
    [Pais.CANADA]: "Canadá",
    [Pais.CATAR]: "Catar",
    [Pais.CAZAQUISTAO]: "Cazaquistão",
    [Pais.CHADE]: "Chade",
    [Pais.CHILE]: "Chile",
    [Pais.CHINA]: "China",
    [Pais.CHIPRE]: "Chipre",
    [Pais.COLOMBIA]: "Colômbia",
    [Pais.COMORES]: "Comores",
    [Pais.CONGO]: "Congo",
    [Pais.COREIA_DO_NORTE]: "Coreia do Norte",
    [Pais.COREIA_DO_SUL]: "Coreia do Sul",
    [Pais.COSTA_DO_MARFIM]: "Costa do Marfim",
    [Pais.COSTA_RICA]: "Costa Rica",
    [Pais.CROACIA]: "Croácia",
    [Pais.CUBA]: "Cuba",
    [Pais.CURACAO]: "Curaçao",
    [Pais.DINAMARCA]: "Dinamarca",
    [Pais.DJIBOUTI]: "Djibouti",
    [Pais.DOMINICA]: "Dominica",
    [Pais.EGITO]: "Egito",
    [Pais.EL_SALVADOR]: "El Salvador",
    [Pais.EMIRADOS_ARABES_UNIDOS]: "Emirados Árabes Unidos",
    [Pais.EQUADOR]: "Equador",
    [Pais.ERITREIA]: "Eritreia",
    [Pais.ESLOVAQUIA]: "Eslováquia",
    [Pais.ESLOVENIA]: "Eslovênia",
    [Pais.ESPANHA]: "Espanha",
    [Pais.ESTADOS_UNIDOS]: "Estados Unidos",
    [Pais.ESTONIA]: "Estônia",
    [Pais.ETIOPIA]: "Etiópia",
    [Pais.FIJI]: "Fiji",
    [Pais.FILIPINAS]: "Filipinas",
    [Pais.FINLANDIA]: "Finlândia",
    [Pais.FRANCA]: "França",
    [Pais.GABAO]: "Gabão",
    [Pais.GAMBIA]: "Gâmbia",
    [Pais.GANA]: "Gana",
    [Pais.GEORGIA]: "Geórgia",
    [Pais.GIBRALTAR]: "Gibraltar",
    [Pais.GRANADA]: "Granada",
    [Pais.GRECIA]: "Grécia",
    [Pais.GROENLANDIA]: "Groenlândia",
    [Pais.GUADALUPE]: "Guadalupe",
    [Pais.GUAM]: "Guam",
    [Pais.GUATEMALA]: "Guatemala",
    [Pais.GUERNSEY]: "Guernsey",
    [Pais.GUINE]: "Guiné",
    [Pais.GUINE_BISSAU]: "Guiné-Bissau",
    [Pais.GUINE_EQUATORIAL]: "Guiné Equatorial",
    [Pais.GUIANA]: "Guiana",
    [Pais.GUIANA_FRANCESA]: "Guiana Francesa",
    [Pais.HAITI]: "Haiti",
    [Pais.HONDURAS]: "Honduras",
    [Pais.HONG_KONG]: "Hong Kong",
    [Pais.HUNGRIA]: "Hungria",
    [Pais.IEMEN]: "Iêmen",
    [Pais.ILHAS_CAYMAN]: "Ilhas Cayman",
    [Pais.ILHAS_COOK]: "Ilhas Cook",
    [Pais.ILHAS_FALKLAND]: "Ilhas Falkland",
    [Pais.ILHAS_MARSHALL]: "Ilhas Marshall",
    [Pais.ILHAS_SALOMAO]: "Ilhas Salomão",
    [Pais.ILHAS_TURCAS_E_CAICOS]: "Ilhas Turcas e Caicos",
    [Pais.ILHAS_VIRGENS_AMERICANAS]: "Ilhas Virgens Americanas",
    [Pais.ILHAS_VIRGENS_BRITANICAS]: "Ilhas Virgens Britânicas",
    [Pais.INDIA]: "Índia",
    [Pais.INDONESIA]: "Indonésia",
    [Pais.IRA]: "Irã",
    [Pais.IRAQUE]: "Iraque",
    [Pais.IRLANDA]: "Irlanda",
    [Pais.ISLANDIA]: "Islândia",
    [Pais.ISRAEL]: "Israel",
    [Pais.ITALIA]: "Itália",
    [Pais.JAMAICA]: "Jamaica",
    [Pais.JAPAO]: "Japão",
    [Pais.JERSEY]: "Jersey",
    [Pais.JORDANIA]: "Jordânia",
    [Pais.KAZAQUISTAO]: "Cazaquistão",
    [Pais.KIRIBATI]: "Kiribati",
    [Pais.KUWAIT]: "Kuwait",
    [Pais.LAOS]: "Laos",
    [Pais.LESOTO]: "Lesoto",
    [Pais.LETONIA]: "Letônia",
    [Pais.LIBANO]: "Líbano",
    [Pais.LIBERIA]: "Libéria",
    [Pais.LIBIA]: "Líbia",
    [Pais.LIECHTENSTEIN]: "Liechtenstein",
    [Pais.LITUANIA]: "Lituânia",
    [Pais.LUXEMBURGO]: "Luxemburgo",
    [Pais.MACAU]: "Macau",
    [Pais.MADAGASCAR]: "Madagascar",
    [Pais.MALASIA]: "Malásia",
    [Pais.MALAUI]: "Malawi",
    [Pais.MALDIVAS]: "Maldivas",
    [Pais.MALI]: "Mali",
    [Pais.MALTA]: "Malta",
    [Pais.MARROCOS]: "Marrocos",
    [Pais.MARTINICA]: "Martinica",
    [Pais.MAURICIO]: "Maurício",
    [Pais.MAURITANIA]: "Mauritânia",
    [Pais.MEXICO]: "México",
    [Pais.MICRONESIA]: "Micronésia",
    [Pais.MOCAMBIQUE]: "Moçambique",
    [Pais.MOLDOVA]: "Moldávia",
    [Pais.MONACO]: "Mônaco",
    [Pais.MONGOLIA]: "Mongólia",
    [Pais.MONTENEGRO]: "Montenegro",
    [Pais.MONTSERRAT]: "Montserrat",
    [Pais.NAMIBIA]: "Namíbia",
    [Pais.NAURU]: "Nauru",
    [Pais.NEPAL]: "Nepal",
    [Pais.NICARAGUA]: "Nicarágua",
    [Pais.NIGER]: "Níger",
    [Pais.NIGERIA]: "Nigéria",
    [Pais.NIUE]: "Niue",
    [Pais.NORUEGA]: "Noruega",
    [Pais.NOVA_CALEDONIA]: "Nova Caledônia",
    [Pais.NOVA_ZELANDIA]: "Nova Zelândia",
    [Pais.OMA]: "Omã",
    [Pais.PAISES_BAIXOS]: "Países Baixos",
    [Pais.PALAU]: "Palau",
    [Pais.PALESTINA]: "Palestina",
    [Pais.PANAMA]: "Panamá",
    [Pais.PAPUA_NOVA_GUINE]: "Papua-Nova Guiné",
    [Pais.PAQUISTAO]: "Paquistão",
    [Pais.PARAGUAI]: "Paraguai",
    [Pais.PERU]: "Peru",
    [Pais.POLINESIA_FRANCESA]: "Polinésia Francesa",
    [Pais.POLONIA]: "Polônia",
    [Pais.PORTUGAL]: "Portugal",
    [Pais.PORTO_RICO]: "Porto Rico",
    [Pais.QATAR]: "Catar",
    [Pais.QUENIA]: "Quênia",
    [Pais.QUIRGUISTAO]: "Quirguistão",
    [Pais.REUNIAO]: "Reunião",
    [Pais.ROMENIA]: "Romênia",
    [Pais.RUANDA]: "Ruanda",
    [Pais.RUSSIA]: "Rússia",
    [Pais.SALVADOR]: "El Salvador",
    [Pais.SAMOA]: "Samoa",
    [Pais.SAN_MARINO]: "San Marino",
    [Pais.SANTA_HELENA]: "Santa Helena",
    [Pais.SANTA_LUCIA]: "Santa Lúcia",
    [Pais.SAO_BARTOLOMEU]: "São Bartolomeu",
    [Pais.SAO_CRISTOVAO_E_NEVIS]: "São Cristóvão e Nevis",
    [Pais.SAO_TOME_E_PRINCIPE]: "São Tomé e Príncipe",
    [Pais.SAO_VICENTE_E_GRANADINAS]: "São Vicente e Granadinas",
    [Pais.SENEGAL]: "Senegal",
    [Pais.SERVIA]: "Sérvia",
    [Pais.SEYCHELLES]: "Seychelles",
    [Pais.SERRA_LEOA]: "Serra Leoa",
    [Pais.SINGAPURA]: "Singapura",
    [Pais.SIRIA]: "Síria",
    [Pais.SOMALIA]: "Somália",
    [Pais.SRI_LANKA]: "Sri Lanka",
    [Pais.SUAZILANDIA]: "Suazilândia",
    [Pais.SUDAO]: "Sudão",
    [Pais.SUDAO_DO_SUL]: "Sudão do Sul",
    [Pais.SUECIA]: "Suécia",
    [Pais.SUICA]: "Suíça",
    [Pais.SURINAME]: "Suriname",
    [Pais.TAILANDIA]: "Tailândia",
    [Pais.TAIWAN]: "Taiwan",
    [Pais.TADJIQUISTAO]: "Tajiquistão",
    [Pais.TANZANIA]: "Tanzânia",
    [Pais.TIMOR_LESTE]: "Timor-Leste",
    [Pais.TOGO]: "Togo",
    [Pais.TONGA]: "Tonga",
    [Pais.TRINIDAD_E_TOBAGO]: "Trinidad e Tobago",
    [Pais.TUNISIA]: "Tunísia",
    [Pais.TURCOMENISTAO]: "Turcomenistão",
    [Pais.TURQUIA]: "Turquia",
    [Pais.TUVALU]: "Tuvalu",
    [Pais.UCRANIA]: "Ucrânia",
    [Pais.UGANDA]: "Uganda",
    [Pais.URUGUAI]: "Uruguai",
    [Pais.UZBEQUISTAO]: "Uzbequistão",
    [Pais.VANUATU]: "Vanuatu",
    [Pais.VATICANO]: "Vaticano",
    [Pais.VENEZUELA]: "Venezuela",
    [Pais.VIETNA]: "Vietnã",
    [Pais.ZAMBIA]: "Zâmbia",
    [Pais.ZIMBABUE]: "Zimbábue"
};