export enum TipoDroga {
  ALCOOL = 'ALCOOL',
  CATITONAS = 'CATITONAS',
  CETAMINA = 'CETAMINA',
  CHA_DE_LIRO = 'CHA_DE_LIRO',
  COCAINA = 'COCAINA',
  COGUMELO = 'COGUMELO',
  COLA_DE_SAPATEIRO = 'COLA_DE_SAPATEIRO',
  CRACK = 'CRACK',
  DMT = 'DMT',
  ECSTASY = 'ECSTASY',
  FENCICLIDINA = 'FENCICLIDINA',
  HAXIXE = 'HAXIXE',
  HEROINA = 'HEROINA',
  K2 = 'K2',
  K4 = 'K4',
  K9 = 'K9',
  KETAMINA = 'KETAMINA',
  LSD = 'LSD',
  MACONHA = 'MACONHA',
  MDMA = 'MDMA',
  MESCALINA = 'MESCALINA',
  METANFETAMINA = 'METANFETAMINA',
  NBOH = 'NBOH',
  NBOHME = 'NBOHME',
  PASTA_BASE_COCAINA = 'PASTA_BASE_COCAINA',
  PCP = 'PCP',
  PE_DE_MACONHA = 'PE_DE_MACONHA',
  PO_DE_ANJO = 'PO_DE_ANJO',
  SOLVENTES_E_INALANTES = 'SOLVENTES_E_INALANTES',
  SPECIAL_K = 'SPECIAL_K'
};

export const TipoDrogaDescricao: Record<TipoDroga, string> = {
  [TipoDroga.ALCOOL]: 'Álcool',
  [TipoDroga.CATITONAS]: 'Catitonas',
  [TipoDroga.CETAMINA]: 'Cetamina',
  [TipoDroga.CHA_DE_LIRO]: 'Chá de liro',
  [TipoDroga.COCAINA]: 'Cocaína',
  [TipoDroga.COGUMELO]: 'Cogumelo',
  [TipoDroga.COLA_DE_SAPATEIRO]: 'Cola de sapateiro',
  [TipoDroga.CRACK]: 'Crack',
  [TipoDroga.DMT]: 'Dimetiltriptamina',
  [TipoDroga.ECSTASY]: 'Ecstasy',
  [TipoDroga.FENCICLIDINA]: 'Fenciclidina',
  [TipoDroga.HAXIXE]: 'Haxixe',
  [TipoDroga.HEROINA]: 'Heroína',
  [TipoDroga.K2]: 'K2',
  [TipoDroga.K4]: 'K4',
  [TipoDroga.K9]: 'K9',
  [TipoDroga.KETAMINA]: 'Ketamina',
  [TipoDroga.LSD]: 'LSD',
  [TipoDroga.MACONHA]: 'Maconha',
  [TipoDroga.MDMA]: 'MDMA',
  [TipoDroga.MESCALINA]: 'Mescalina',
  [TipoDroga.METANFETAMINA]: 'Metanfetamina',
  [TipoDroga.NBOH]: 'NBOH',
  [TipoDroga.NBOHME]: 'NBOHME',
  [TipoDroga.PASTA_BASE_COCAINA]: 'Pasta base cocaína',
  [TipoDroga.PCP]: 'PCP',
  [TipoDroga.PE_DE_MACONHA]: 'Pé de maconha',
  [TipoDroga.PO_DE_ANJO]: 'Pó de anjo',
  [TipoDroga.SOLVENTES_E_INALANTES]: 'Solventes e inalantes',
  [TipoDroga.SPECIAL_K]: 'Special K'
};
