export enum TipoVeiculo {  
    AUTOMOVEL = 'AUTOMOVEL',
    MOTOCICLETA = 'MOTOCICLETA',
    MOTONETA = 'MOTONETA',
    CAMINHONETE = 'CAMINHONETE',
    CAMINHAO = 'CAMINHAO',
    CAMIONETA = 'CAMIONETA',
    UTILITARIO = 'UTILITARIO',
    MICRO_ONIBUS = 'MICRO_ONIBUS',
    ONIBUS = 'ONIBUS',
    CAMINHAO_TRATOR = 'CAMINHAO_TRATOR',
    TRICICLO = 'TRICICLO',
    QUADRICICLO = 'QUADRICICLO',
    REBOQUE = 'REBOQUE',
    SEMIRREBOQUE = 'SEMIRREBOQUE',
    TRATOR = 'TRATOR',
    MOTOR_CASA = 'MOTOR_CASA',
}

export const TipoVeiculoDescricao: Record<TipoVeiculo, string> = {
    [TipoVeiculo.AUTOMOVEL]: 'Automóvel',
    [TipoVeiculo.MOTOCICLETA]: 'Motocicleta',
    [TipoVeiculo.MOTONETA]: 'Motoneta',
    [TipoVeiculo.CAMINHONETE]: 'Caminhonete',
    [TipoVeiculo.CAMINHAO]: 'Caminhão',
    [TipoVeiculo.CAMIONETA]: 'Camioneta',
    [TipoVeiculo.UTILITARIO]: 'Utilitário',
    [TipoVeiculo.MICRO_ONIBUS]: 'Micro-ônibus',
    [TipoVeiculo.ONIBUS]: 'Ônibus',
    [TipoVeiculo.CAMINHAO_TRATOR]: 'Caminhão-trator',
    [TipoVeiculo.TRICICLO]: 'Triciclo',
    [TipoVeiculo.QUADRICICLO]: 'Quadriciclo',
    [TipoVeiculo.REBOQUE]: 'Reboque',
    [TipoVeiculo.SEMIRREBOQUE]: 'Semirreboque',
    [TipoVeiculo.TRATOR]: 'Trator',
    [TipoVeiculo.MOTOR_CASA]: 'Motor-casa',
};